version: '2'

#will create this network if it does not exist
networks:
  node-red-net:

volumes:
    node-red-data:
    mariadb_config:
    mariadb_data:
    mosq_config:
    mosq_data:
    mosq_log:
    graf_data:
    graf_log:
    resin-data:

services:
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    #privileged: true
    #network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.build.description: ' https://github.com/barneymc/balena-node-red - Node red service testing Brendan 1'
    environment:
      - "USERNAME=balena"
      - "PASSWORD=balena"
      - "ENCRIPTION_KEY=balena"
      -  GIT_URL="https://github.com/barneymc/balena-node-red"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 80:80
    networks:
      - node-red-net


 # ------------------------------------------------------------------------------------
  # MQTT
  # ------------------------------------------------------------------------------------
  mosquitto:
    build:      
      context: ./mosquitto
    #hostname: mosquitto
    #image: eclipse-mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      #- ./mosquitto.conf:/mosquitto/config/mosquitto.conf     #notice relative path here 
      #- mosq_config:/mosquitto/config/mosquitto-no-auth.conf     #notice relative path here 
      - mosq_config:/mosquitto/config
      - mosq_data:/mosquitto/data
      - mosq_log:/mosquitto/log
    networks:
      - node-red-net
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf"]



